### PR TITLE
Leaderboard setup

### PR DESCRIPTION
**Pull request by erickhansx**
## Checklist before requesting a review
- [x] I have performed a self-review of my code
- [x] I created the HTML file and added the basic structure of the project.
- [x] I used a JavaScript function to display the scores in the HTML when the document loads. 
- [x] I added the basic CSS to adjust the structure of the page.

### CODE REVIEW

**Review by omar-muhamad — APPROVED** [review]
# Invalid ❌

Hi @erickhansx,

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

Your Code Review Request is marked as invalid for these reasons:

- [x] You didn't document your work professionally:
   - You forgot to add your README file. Please use the Microverse README template and edit it with your personal and project data.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **Does not count** into the code reviews limit._

**Comment by erickhansx** [comment]
@Omar-Muhamad Thank you for your observation! I was so focused on learning about APIs that I completely forgot about the README. Again, thank you so much for letting me know about my mistake and I will fix it ASAP. Regards!
PrayingCatGIF

**Comment by erickhansx** [comment]
> # Invalid ❌
> Hi @erickhansx,
> 
> While you made a great effort in this project, unfortunately, I cannot proceed to review your code.
> 
> Your Code Review Request is marked as invalid for these reasons:
> 
> * [ ]  You didn't document your work professionally:
>   
>   * You forgot to add your README file. Please use the Microverse README template and edit it with your personal and project data.
> 
> Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏
> 
> Cheers and Happy coding!👏👏👏
> 
> Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.
> 
> **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**
> 
> _Invalid Code Review Request **Does not count** into the code reviews limit._

**Review by omar-muhamad — APPROVED** [review]
# Approved ✔
### Hi @erickhansx,

Great job, Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

thumbs-up-agree


## (Highlights) Good Points: :+1:
- You documented your work professionally. ✔
- You used the correct workflow.  ✔
- All linters checks are ok. ✔

## (Changes Required) Aspects to improve: ♻️

- N/A

## [Optional] suggestions:

- N/A

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

**Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear, and please remember to tag me in your question so I can receive the notification**

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

**Pull request merged**
